### PR TITLE
[MINOR] Fix for Member List

### PR DESCRIPTION
**Pull request by AHIRAISSHY**
Fixes # The member list colors same with Group Chats

Fix1
FixGC

### CODE REVIEW

**Comment by Strencher** [comment]
you also need to build the `import.css`

**Comment by AHIRAISSHY** [comment]
> you also need to build the `import.css`

as my own?

**Comment by Strencher** [comment]
Yes, clone the repo into a folder do `npm install`  -> `npm run build` -> `npm run import`
(if i remember correctly)

**Comment by AHIRAISSHY** [comment]
> Yes, clone the repo into a folder do `npm install` -> `npm run build` -> `npm run import`
> (if i remember correctly)

ight thanks i'm doing that rn

**Comment by AHIRAISSHY** [comment]
@Strencher does this matter?
```js
[12:27:29] Using gulpfile ~\OneDrive\Documentos\GitHub\Nox\gulpfile.js
[12:27:29] Starting 'sass'...
(node:11088) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

<--- Last few GCs --->

[11088:0000019C0B885D80]  1058452 ms: Scavenge 2044.4 (2049.1) -> 2043.6 (2049.1) MB, 7.3 / 0.0 ms  (average mu = 0.358, current mu = 0.342) allocation failure
[11088:0000019C0B885D80]  1058479 ms: Scavenge 2044.5 (2049.1) -> 2043.7 (2051.1) MB, 6.5 / 0.0 ms  (average mu = 0.358, current mu = 0.342) allocation failure
[11088:0000019C0B885D80]  1058533 ms: Scavenge 2045.7 (2051.1) -> 2043.9 (2051.4) MB, 7.2 / 0.0 ms  (average mu = 0.358, current mu = 0.342) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7C1255F0F napi_wrap+114095
 2: 00007FF7C1200B96 v8::base::CPU::has_sse+66998
 3: 00007FF7C1201996 v8::base::CPU::has_sse+70582
 4: 00007FF7C1A16E9E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7C19FEF71 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7C18CB1DC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7C18D6410 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7C18D2F34 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7C18C8733 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7C18CB32A v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1770
11: 00007FF7C18C18F3 v8::base::CPU::has_vfp3+467
12: 00007FF7C119861F std::basic_ostream<char,std::char_traits<char> >::operator<<+72191
13: 00007FF7C1197674 std::basic_ostream<char,std::char_traits<char> >::operator<<+68180
14: 00007FF7C12A67CB uv_async_send+331
15: 00007FF7C12A5F6C uv_loop_init+1212
16: 00007FF7C12A6134 uv_run+244
17: 00007FF7C11B6F61 v8::internal::Scope::locals+31841
18: 00007FF7C122A5E3 node::Start+275
19: 00007FF7C1096A9C RC4_options+340380
20: 00007FF7C1F23588 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
21: 00007FFAD1757BD4 BaseThreadInitThunk+20
22: 00007FFAD1FACE51 RtlUserThreadStart+33
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! nox@1.0.4-patch1 build: `gulp sass`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the nox@1.0.4-patch1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KoalaBeans\AppData\Roaming\npm-cache\_logs\2020-10-10T16_45_08_663Z-debug.log
```

**Comment by AHIRAISSHY** [comment]
There is something more that needs to be fixed..

It's the fact that the last member offline is half shown

**Comment by AHIRAISSHY** [comment]
UPDATED TO #21

**Pull request closed without merging**
